[package]
name = "colo"
version = "0.1.0"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.1" 
clap = "2" 
color_space = "=0.5.2" # TODO: This version has a few bugs for which I have hacky workarounds. Fix the bugs upstream, then update this dep and remove the workarounds
anyhow = "1"
