[package]
name = "colo"
version = "0.2.1"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
description = "CLI tool to show and convert colors between various color spaces"
categories = ["command-line-interface"]
repository = "https://github.com/Aloso/colo"
documentation = "https://docs.rs/colo"
homepage = "https://github.com/Aloso/colo"
readme = "README.md"
exclude = ["docs/*"]
edition = "2018"

keywords = ["color", "cli"]
license = "MIT"

[dependencies]
crossterm = "0.18.1" 
clap = "2" 
color_space = "=0.5.2" # TODO: This version has a few bugs for which I have hacky workarounds. Fix the bugs upstream, then update this dep and remove the workarounds
anyhow = "1"
