edition = "2018"
blank_lines_upper_bound = 2
format_code_in_doc_comments = true
match_arm_leading_pipes = "Preserve"
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true
